spring.application.name=textseries

# Server Port
server.port=8181

# MySQL Configuration
spring.datasource.url=jdbc:mysql://auth-db1947.hstgr.io:3306/u633320633_textSeries?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata&connectTimeout=5000&socketTimeout=5000
spring.datasource.username=u633320633_Lalit
spring.datasource.password=81KAVIndra

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# Mail service 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kavindrasingh7535@gmail.com
spring.mail.password=rord gjfb qwgf nuzn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




## Connection Pool 
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.keepalive-time=30000